### ISSUE TITLE
ubuntu源码编译报错，请开发组帮忙看一下

### ISSUE THREAD

**Issue by MTleen** [BitcoinGod/BitcoinGod#1]
系统版本：Ubuntu 18.04 LTS
依赖已按照官网的教程安装完毕，地址：https://blog.bitcoingod.org/index.php/2018/05/03/bitcoingod-installation/#more-43
已尝试重新clone源码
在执行make操作时报如下错，请开发组帮忙看一下，谢谢。
![makeerror](https://user-images.githubusercontent.com/23020089/39630276-7759abcc-4fe1-11e8-96a1-5cf19251e258.png)

**Comment by xixisese** [comment]
What version of OpenSSL on your platform?

**Comment by MTleen** [comment]
您好，是1.1.0

**Comment by xixisese** [comment]
It's the library dependency issue . try to run the "sudo apt-get install libssl1.0-dev". then make again
