### ISSUE TITLE
The client is taking forever to download the blockchain, please provide nodes for us.

### ISSUE THREAD

**Issue by Hesham3del** [BitcoinGod/BitcoinGod#2]
Hey all,

The client is taking forever to download the blockchain, although it's connected to 5 nodes and this problem was not present when you uploaded the first version of the client, please provide nodes for us or tell us about a method to make the download go faster.

Here is a screenshot : https://ibb.co/bWrNao

Thanks you :)

**Comment by BitcoinGod** [comment]
pls check blog.

https://blog.bitcoingod.org/index.php/2018/05/26/bitcoingod-fast-block-initialize-solution/#more-177
