### ISSUE TITLE
The debug.log file is so huge during mining

### ISSUE THREAD

**Issue by tangpinggou** [BitcoinGod/BitcoinGod#3]
RT
How to do?
THX

**Comment by BitcoinGod** [comment]
u can delete it at anytime.

**Comment by tangpinggou** [comment]
手动删除太麻烦了，可不可以不写日志

**Comment by tangpinggou** [comment]
If i wanna del the debug.log file under windows i had to shutdown bitcoingod core first. So the cron can't run successfully. Is there any way to solve this problem? Don't write log or auto del it.

**Comment by duanfp** [comment]
for now, the file just can manully delete it, but the suggestion so good, we will record it and fix it at next version. thank u
