### ISSUE TITLE
你们这个项目到底还维不维护?

### ISSUE THREAD

**Issue by wupeaking** [BitcoinGod/BitcoinGod#5]
-  有没有自己的测试链？

-  如果说使用的和比特币相同的测试链，为什么同步一段时间就会异常退出？

如图:

![image](https://user-images.githubusercontent.com/15843348/41270204-77a17dd4-6e3c-11e8-8636-287a71062a70.png)

环境: 
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

版本: v0.1.3.0

**Comment by wupeaking** [comment]
@xixisese @shepherd417 @BitcoinGod 期待回复。

**Comment by BananaLF** [comment]
The BitcoinGod testnet coming soon. The problem will be solved in the near future.
