### ISSUE TITLE
Base tag v1.0.4.0 why not find bitcoingodd  ?

### ISSUE THREAD

**Issue by guchenglin111** [BitcoinGod/BitcoinGod#6]
bitcoingodd  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 88  -datadir=../../.bitcoingod -rpcuser=gu123456 -rpcpassword=hx20180907 --testnet -daemon

why not find bitcoingodd  ?

**Comment by BananaLF** [comment]
Frist problem ,I think you haven't excute sudo make install. you can input sudo make install.
Second proble, you should uses follow command.
-rpcbind=<addr>[:port]
